### ISSUE TITLE
NS not connecting to devices...

### ISSUE THREAD

**Issue by ewhite122** [jamespauly/udi-tuya-poly#5]
am i doing something wrong? log:

2022-11-29 13:16:25,955 Thread-3   udi_interface.interface INFO     interface:addNode: Adding node Shop Outside Light(eb04287442) [None]
2022-11-29 13:16:25,956 Thread-3   udi_interface.interface DEBUG    interface:send: PUBLISHING {'addnode': [{'address': 'eb04287442', 'name': 'Shop Outside Light', 'nodeDefId': 'tuyanode', 'primaryNode': 'controller', 'drivers': [{'driver': 'ST', 'value': 1, 'uom': 2}, {'driver': 'GV1', 'value': 0, 'uom': 51}, {'driver': 'GV2', 'value': 0, 'uom': 45}, {'driver': 'GV3', 'value': 0, 'uom': 25}], 'hint': [0, 0, 0, 0], 'private': None, 'rename': False}]}
2022-11-29 13:16:25,958 Thread-3   udi_interface      INFO     TuyaController:discover: Device Scan Device IP: 192.168.10.166
2022-11-29 13:16:25,959 Thread-3   udi_interface      INFO     TuyaController:discover: Device Scan Device IP: 192.168.10.171
2022-11-29 13:16:25,959 Thread-3   udi_interface      INFO     TuyaController:discover: Device Scan Device IP: 192.168.10.253
2022-11-29 13:16:25,960 Thread-3   udi_interface      INFO     TuyaController:discover: Finished Tuya Device Discovery
2022-11-29 13:16:26,232 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message addnode
2022-11-29 13:16:26,234 Command    udi_interface.interface DEBUG    interface:_parseInput: DEQUEING addnode
2022-11-29 13:16:26,236 Thread-9   udi_interface      INFO     TuyaNode:query: Query sensor eb04287442
2022-11-29 13:16:26,238 Command    udi_interface.interface DEBUG    interface:_handleResult: add node response: {'id': '1eef8a63-c261-49b0-84fd-8a74e697db25', 'uuid': '00:0d:b9:5d:9d:ac', 'profileNum': 17, 'address': 'eb04287442', 'name': 'Shop Outside Light', 'nodeDefId': 'tuyanode', 'nls': None, 'hint': '0x00000000', 'controller': 0, 'primaryNode': 'controller', 'private': None, 'isPrimary': 0, 'enabled': 1, 'timeAdded': 1669748446121, 'timeModified': 1669748446121, 'dbVersion': 1}
2022-11-29 13:16:26,238 Thread-9   udi_interface      INFO     TuyaNode:query: Node Name Shop Outside Light
2022-11-29 13:16:46,292 Thread-9   udi_interface      INFO     TuyaNode:query: Node Status {'Error': 'Network Error: Device Unreachable', 'Err': '905', 'Payload': None}
2022-11-29 13:16:46,293 Thread-9   udi_interface      ERROR    udi_interface:write: Exception in thread
2022-11-29 13:16:46,294 Thread-9   udi_interface      ERROR    udi_interface:write: Thread-9
2022-11-29 13:16:46,296 Thread-9   udi_interface      ERROR    udi_interface:write: :
2022-11-29 13:16:46,297 Thread-9   udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-29 13:16:46,298 Thread-9   udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2022-11-29 13:16:46,303 Thread-9   udi_interface      ERROR    udi_interface:write: self.run()
2022-11-29 13:16:46,305 Thread-9   udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 917, in run
2022-11-29 13:16:46,309 Thread-9   udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-11-29 13:16:46,310 Thread-9   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d9dac_17/nodes/TuyaNode.py", line 53, in start
2022-11-29 13:16:46,312 Thread-9   udi_interface      ERROR    udi_interface:write: self.query()
2022-11-29 13:16:46,314 Thread-9   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d9dac_17/nodes/TuyaNode.py", line 34, in query
2022-11-29 13:16:46,316 Thread-9   udi_interface      ERROR    udi_interface:write: node_brightness = node_status['dps']['107']/10
2022-11-29 13:16:46,317 Thread-9   udi_interface      ERROR    udi_interface:write: KeyError
2022-11-29 13:16:46,318 Thread-9   udi_interface      ERROR    udi_interface:write: :
2022-11-29 13:16:46,319 Thread-9   udi_interface      ERROR    udi_interface:write: 'dps'
2022-11-29 13:18:00,237 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message query
2022-11-29 13:18:00,239 Command    udi_interface.interface DEBUG    interface:_parseInput: DEQUEING query
2022-11-29 13:18:00,240 Command    udi_interface      INFO     TuyaNode:query: Query sensor eb04287442
2022-11-29 13:18:00,240 Command    udi_interface      INFO     TuyaNode:query: Node Name Shop Outside Light
2022-11-29 13:18:05,723 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message command
2022-11-29 13:18:30,316 Command    udi_interface      INFO     TuyaNode:query: Node Status {'Error': 'Network Error: Device Unreachable', 'Err': '905', 'Payload': None}
2022-11-29 13:18:30,318 Command    udi_interface      ERROR    udi_interface:write: Exception in thread
2022-11-29 13:18:30,319 Command    udi_interface      ERROR    udi_interface:write: Command
2022-11-29 13:18:30,319 Command    udi_interface      ERROR    udi_interface:write: :
2022-11-29 13:18:30,320 Command    udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-29 13:18:30,321 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
2022-11-29 13:18:30,326 Command    udi_interface      ERROR    udi_interface:write: self.run()
2022-11-29 13:18:30,328 Command    udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/threading.py", line 917, in run
2022-11-29 13:18:30,332 Command    udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-11-29 13:18:30,333 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 764, in _parseInput
2022-11-29 13:18:30,337 Command    udi_interface      ERROR    udi_interface:write: self._handleInput(key, input[key], None)
2022-11-29 13:18:30,338 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/udi_interface/interface.py", line 895, in _handleInput
2022-11-29 13:18:30,343 Command    udi_interface      ERROR    udi_interface:write: self.nodes_internal[item['address']].query()
2022-11-29 13:18:30,344 Command    udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95d9dac_17/nodes/TuyaNode.py", line 34, in query
2022-11-29 13:18:30,346 Command    udi_interface      ERROR    udi_interface:write: node_brightness = node_status['dps']['107']/10
2022-11-29 13:18:30,348 Command    udi_interface      ERROR    udi_interface:write: KeyError
2022-11-29 13:18:30,348 Command    udi_interface      ERROR    udi_interface:write: :
2022-11-29 13:18:30,349 Command    udi_interface      ERROR    udi_interface:write: 'dps'
2022-11-29 13:20:22,778 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message shortPoll
2022-11-29 13:25:22,803 MQTT       udi_interface.interface DEBUG    interface:_message: QUEUING incoming message longPoll

**Comment by sjpbailey** [comment]
Hey James!
Probably not you! I dialed it with Pandas for my type of devices, so we will probably have to talk while testing. 
I Made that one to see if we got lucky it will need to be broken down in test programs to test routines, outside of Node Server running.

**Comment by sjpbailey** [comment]
Morning James,
 I built this with Wizard in the controller and I need to resolve the name to get it to connect.
 I will add it as tuya_ctl.py this is doing append with the wizard crammed into it with the following errors.
 The 'client_id': <nodes.tuya_ctl.Controller object at 0x806848e80> has the name wrong so Idk too much of a rookie still!
 
Payload Sent
```
 2022-11-30 04:00:02,106 Thread-3   udi_interface      INFO     tuya_ctl:tuyaPlatform: Payload Sent
<nodes.tuya_ctl.Controller object at 0x806848e80>1669809602104GET
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
/v1.0/token?grant_type = 1
2022-11-30 04:00:02,107 Thread-3   udi_interface      INFO     tuya_ctl:tuyaPlatform: Headers
{'secret': '46d6072ffd724e0ba5ebeb5cc6b9dce9', 'client_id': <nodes.tuya_ctl.Controller object at 0x806848e80>, 'sign': '917162FBD7E4299CB9B6285BB7668D454F40BE56DEE571A55419DF35C15949F4', 't': '1669809602104', 'sign_method': 'HMAC-SHA256', 'access_token': 'txejpdfda9iwmn5cg2es'}
2022-11-30 04:00:02,151 MQTT       udi_interface.interface INFO     interface:_message: custom data response {'customparamsdoc': '<h1>Tuya LED Controller</h1>\n'}
2022-11-30 04:00:02,189 MQTT       udi_interface.interface INFO     interface:_message: Successfully set key = customparamsdoc
2022-11-30 04:00:02,284 Thread-3   udi_interface      ERROR    udi_interface:write: Exception in thread
2022-11-30 04:00:02,285 Thread-3   udi_interface      ERROR    udi_interface:write: Thread-3
2022-11-30 04:00:02,286 Thread-3   udi_interface      ERROR    udi_interface:write: :
2022-11-30 04:00:02,287 Thread-3   udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-30 04:00:02,287 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
2022-11-30 04:00:02,291 Thread-3   udi_interface      ERROR    udi_interface:write: conn = connection.create_connection(
2022-11-30 04:00:02,292 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
2022-11-30 04:00:02,294 Thread-3   udi_interface      ERROR    udi_interface:write: for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2022-11-30 04:00:02,295 Thread-3   udi_interface      ERROR    udi_interface:write: File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
2022-11-30 04:00:02,300 Thread-3   udi_interface      ERROR    udi_interface:write: for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2022-11-30 04:00:02,301 Thread-3   udi_interface      ERROR    udi_interface:write: socket
2022-11-30 04:00:02,302 Thread-3   udi_interface      ERROR    udi_interface:write: .
2022-11-30 04:00:02,303 Thread-3   udi_interface      ERROR    udi_interface:write: gaierror
2022-11-30 04:00:02,304 Thread-3   udi_interface      ERROR    udi_interface:write: :
2022-11-30 04:00:02,305 Thread-3   udi_interface      ERROR    udi_interface:write: [Errno 8] Name does not resolve
2022-11-30 04:00:02,305 Thread-3   udi_interface      ERROR    udi_interface:write: During handling of the above exception, another exception occurred:
2022-11-30 04:00:02,306 Thread-3   udi_interface      ERROR    udi_interface:write: Traceback (most recent call last)
```

Name Not Resolved Error
```
 File "/usr/local/lib/python3.9/threading.py", line 917, in run
2022-11-30 04:00:02,364 Thread-3   udi_interface      ERROR    udi_interface:write: self._target(*self._args, **self._kwargs)
2022-11-30 04:00:02,366 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95608ec_3/nodes/tuya_ctl.py", line 117, in start
2022-11-30 04:00:02,368 Thread-3   udi_interface      ERROR    udi_interface:write: self.tuyaPlatform(self, self.apiSecret, self.apiKey, self.apiRegion)
2022-11-30 04:00:02,370 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db95608ec_3/nodes/tuya_ctl.py", line 166, in tuyaPlatform
2022-11-30 04:00:02,371 Thread-3   udi_interface      ERROR    udi_interface:write: response = requests.get(url, headers)
2022-11-30 04:00:02,372 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/requests/api.py", line 75, in get
2022-11-30 04:00:02,375 Thread-3   udi_interface      ERROR    udi_interface:write: return request('get', url, params=params, **kwargs)
2022-11-30 04:00:02,376 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/requests/api.py", line 61, in request
2022-11-30 04:00:02,378 Thread-3   udi_interface      ERROR    udi_interface:write: return session.request(method=method, url=url, **kwargs)
2022-11-30 04:00:02,379 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
2022-11-30 04:00:02,383 Thread-3   udi_interface      ERROR    udi_interface:write: resp = self.send(prep, **send_kwargs)
2022-11-30 04:00:02,384 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
2022-11-30 04:00:02,388 Thread-3   udi_interface      ERROR    udi_interface:write: r = adapter.send(request, **kwargs)
2022-11-30 04:00:02,389 Thread-3   udi_interface      ERROR    udi_interface:write: File "/var/polyglot/.local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
2022-11-30 04:00:02,392 Thread-3   udi_interface      ERROR    udi_interface:write: raise ConnectionError(e, request=request)
2022-11-30 04:00:02,393 Thread-3   udi_interface      ERROR    udi_interface:write: requests.exceptions
2022-11-30 04:00:02,393 Thread-3   udi_interface      ERROR    udi_interface:write: .
2022-11-30 04:00:02,394 Thread-3   udi_interface      ERROR    udi_interface:write: ConnectionError
2022-11-30 04:00:02,395 Thread-3   udi_interface      ERROR    udi_interface:write: :
2022-11-30 04:00:02,396 Thread-3   udi_interface      ERROR    udi_interface:write: HTTPSConnectionPool(host='openapi.tuya%3cnodes.tuya_ctl.controller%20object%20at%200x806848e80%3e.com', port=443): Max retries exceeded with url: /v1.0/token?grant_type%20=%201&secret=46d6072ffd724e0ba5ebeb5cc6b9dce9&client_id=%3Cnodes.tuya_ctl.Controller+object+at+0x806848e80%3E&sign=917162FBD7E4299CB9B6285BB7668D454F40BE56DEE571A55419DF35C15949F4&t=1669809602104&sign_method=HMAC-SHA256&access_token=txejpdfda9iwmn5cg2es (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x80687c820>: Failed to establish a new connection: [Errno 8] Name does not resolve'))
2022-11-30 04:00:02,603 MQTT       udi_interface.interface INFO     interface:_message: Profile installation finished

```

**Comment by jamespauly** [comment]
@ewhite122 How many devices do you have?  It looks like 3.  Are they all light devices?

Regards,
James

**Comment by jamespauly** [comment]
@sjpbailey When you say wizard I assume you mean the tinytuya wizard.

Couple of items.  I'm not sure why you are trying to call the API's directly.  Starting with line 122 in your forked code.

Look at wizard.py inside of the tinytuya package.  If you are just trying to get the decryption key for a device that is all you should need.

Also on the discovery in the controller.  We can take it out but it should not cause and issue as it should check if the existing nodes is already there.  It should not be duplicating.  If it is then that's a bug on my side.  I'm starting to get back into the code again so we can align soon.

Regards,
James

**Comment by sjpbailey** [comment]
Hello James,I have 11 devices and yes it is wizard inserted. LED' and Switches along with PIA (proximity sensors) that do not show their IP address as they go to sleep after a report millisecond online.Trying locally does not give you a consistent grab of devices KEY hangs up during the append.  Wizard does the append best using your credentials like a typical API. Every time i grab IP addresses with the controller combining your old node with your controller works. However once again it would hang on KEY if it found the key for the device then it would give said devices their status json. IP works fantastic key to get data hangs.If it hit it every time then it would be great.I based all of mine on snapshot json dumps to get DPS values to determine which is type i have a light DPS 20 or a switch DPS 1.Then Pandas sorts the data to ADNODE.On Dec 2, 2022, at 7:10 AM, jamespauly ***@***.***> wrote:﻿
@ewhite122 How many devices do you have?  It looks like 3.  Are they all light devices?
Regards,
James

**Comment by ewhite122** [comment]
I have 2 devices right now...looking at adding more if this NS would work out as these TUYA devices are cheap as chips on Amazon...
I think the third you are seeing is the controller?
Also i am manually inputting the info thru config panel as my devices have a public ip outside of my network. so the self discovery would not work.

**Comment by jamespauly** [comment]
Ah okay we are making some changes right now and I'm starting to dig through the code a bit.  At first I only had a bulb device.  Also Tuya has changed they way they do API registration so I'm working through that as well.  @sjpbailey is making some awesome changes as well.  I really don't like how Tuya has set up everything it make setting up devices a nightmare if you don't use there app.

**Comment by ewhite122** [comment]
agreed...

**Comment by ewhite122** [comment]
qwik question...how come you cant make it so you just use your smartlife app credentials to get device info? and change device status thru that also? is it because your trying to keep it local?
just curious...

**Comment by sjpbailey** [comment]
Head on the nail! I think i need to add a class for tuyaplatform to get it to go.I would like to see it as credentials for your API at tuya then TinyTuya wizard grab and throws the local devices.In other words the device snapshot.json. Then i am separating each with Pandas, and have two nodes that currently work my TreatLife LEDs and Switches.Currently i load snapshot.json after running wizard first making my local poly polling my devices only. Then i loads the snapshot.json and it loads all 11 of my devices.If we have wizard do that in the controller then we are $$.So if you get a chance to look at tuya_ctl.py and see a quick fix that would be awesome.Currently not able to pass platform because it is a tuple. I will detail where i am in the scrip. If you can load it and run it, it would be way quicker.Argh, Doh and duh were used lots as I have been working on this on and off for two years. 😂 I have only been writing Python code for three years so i am slow! Also my terminology sucks for describing my exceptions.So if we get Wizard into a controller functional them we can start to add everyones devices using pandas to separate device types.So glad you were working on this i just want to be able to add my TreatLife Cheap devices.Cheers, i will get a chance to look later today as i am also handicapped and cannot sit for too long.RegardsOn Dec 5, 2022, at 6:30 AM, jamespauly ***@***.***> wrote:﻿
Ah okay we are making some changes right now and I'm starting to dig through the code a bit.  At first I only had a bulb device.  Also Tuya has changed they way they do API registration so I'm working through that as well.  @sjpbailey is making some awesome changes as well.  I really don't like how Tuya has set up everything it make setting up devices a nightmare if you don't use there app.

**Comment by ewhite122** [comment]
i realize this is for web.. but i found this..
https://www.reddit.com/r/smartlife/comments/gj5ixd/smart_life_web_interface/

maybe some good info??
